substitutions:
  _REGION: "europe-west1"
  _PROJECT_ID: "jeremy-tkuhscmw"
steps:
  # Build and tag using commit sha
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '.', '-t', '$_REGION-docker.pkg.dev/$_PROJECT_ID/run-image/load-csv:$COMMIT_SHA', '-f', 'Dockerfile']
    dir: 'app'
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_REGION-docker.pkg.dev/$_PROJECT_ID/run-image/load-csv:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        gcloud run services update load-csv --project=$_PROJECT_ID --image=$_REGION-docker.pkg.dev/$_PROJECT_ID/run-image/load-csv:$COMMIT_SHA --region=$_REGION
options:
  logging: CLOUD_LOGGING_ONLY