substitutions:
  _REGION: "europe-west1"
  _PROJECT_ID: "jeremy-tkuhscmw"
steps:
  # Build and tag using commit sha
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '.', '-t', '$_REGION-docker.pkg.dev/$_PROJECT_ID/run-image/load-csv:$COMMIT_SHA', '-f', 'Dockerfile']
    dir: 'app'
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_REGION-docker.pkg.dev/$_PROJECT_ID/run-image/load-csv:$COMMIT_SHA']
  - name: hashicorp/terraform:1.4.6
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd terraform
        terraform init
  - name: hashicorp/terraform:1.4.6
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd terraform
        terraform apply -var "load-csv-sha=$COMMIT_SHA" -auto-approve 
options:
  logging: CLOUD_LOGGING_ONLY